In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('distancias_tiempos2.csv')
df

Distance Duration
0         0.000     0:00
1        15.260     0:22
2        14.930     0:17
3        23.420     0:33
4         9.490     0:12
...         ...      ...
11231    38.365    00:44
11232     9.674    00:24
11233    12.298    00:27
11234     5.247    00:17
11235     0.000    00:00

[11236 rows x 2 columns]

In [66]:
df['Duration'] = pd.to_datetime(df['Duration'])

In [67]:
df['Duration'] = df['Duration'].dt.strftime('%H:%M')

In [68]:
df['Duration']=df['Duration'].astype('string')

In [69]:
df['Duration'].value_counts()

00:16    459
00:14    453
00:20    439
00:22    425
00:18    415
        ... 
01:37      2
01:32      2
01:36      1
01:42      1
01:35      1
Name: Duration, Length: 98, dtype: Int64

In [71]:

def convert_to_seconds(time_str):
    hours, minutes = map(int, time_str.split(':'))
    total_seconds = hours * 3600 + minutes * 60
    return total_seconds

# Apply the conversion function to the DataFrame column
df['Segundos'] = df['Duration'].apply(convert_to_seconds)

print(df)

       Distance Duration  Segundos
0         0.000    00:00         0
1        15.260    00:22      1320
2        14.930    00:17      1020
3        23.420    00:33      1980
4         9.490    00:12       720
...         ...      ...       ...
11231    38.365    00:44      2640
11232     9.674    00:24      1440
11233    12.298    00:27      1620
11234     5.247    00:17      1020
11235     0.000    00:00         0

[11236 rows x 3 columns]


In [ ]:
df.to_numpy()

array([['Depot', 'Depot', 0.0, '00:00:00', 0],
       ['Depot', 'Customer 1', 15.264, '00:22:00', 1320],
       ['Depot', 'Customer 2', 14.929, '00:17:00', 1020],
       ...,
       ['Customer 48', 'Customer 103', 3.988, '00:11:00', 660],
       ['Customer 48', 'Customer 104', 8.956, '00:20:00', 1200],
       ['Customer 48', 'Customer 105', 15.076, '00:25:00', 1500]],
      dtype=object)

In [4]:
rangos = np.arange(0,11236,106)
rangos

array([    0,   106,   212,   318,   424,   530,   636,   742,   848,
         954,  1060,  1166,  1272,  1378,  1484,  1590,  1696,  1802,
        1908,  2014,  2120,  2226,  2332,  2438,  2544,  2650,  2756,
        2862,  2968,  3074,  3180,  3286,  3392,  3498,  3604,  3710,
        3816,  3922,  4028,  4134,  4240,  4346,  4452,  4558,  4664,
        4770,  4876,  4982,  5088,  5194,  5300,  5406,  5512,  5618,
        5724,  5830,  5936,  6042,  6148,  6254,  6360,  6466,  6572,
        6678,  6784,  6890,  6996,  7102,  7208,  7314,  7420,  7526,
        7632,  7738,  7844,  7950,  8056,  8162,  8268,  8374,  8480,
        8586,  8692,  8798,  8904,  9010,  9116,  9222,  9328,  9434,
        9540,  9646,  9752,  9858,  9964, 10070, 10176, 10282, 10388,
       10494, 10600, 10706, 10812, 10918, 11024, 11130])

In [74]:
cuadrada = []
for i in range(len(rangos)-1):
    cuadrada.append(list((df['Segundos'][rangos[i]:rangos[i+1]])))
result_array = np.append(np.array(cuadrada), [(df['Segundos'][rangos[-1]:])], axis = 0)
result_array.shape

(106, 106)

In [75]:
result_array

array([[   0, 1320, 1020, ..., 1320, 1680, 2520],
       [1320,    0, 1380, ...,  360, 1320, 1620],
       [1200, 1440,    0, ..., 1440, 1680, 2520],
       ...,
       [1260,  360, 1320, ...,    0, 1320, 1860],
       [1800, 1320, 1680, ..., 1440,    0,  660],
       [2220, 1560, 2700, ..., 1620, 1020,    0]], dtype=int64)

In [6]:
cuadrada = []
for i in range(len(rangos)-1):
    cuadrada.append(list((df['Distance'][rangos[i]:rangos[i+1]])))
resulta_array = np.append(np.array(cuadrada), [(df['Distance'][rangos[-1]:])], axis = 0)
resulta_array

array([[ 0.   , 15.26 , 14.93 , ..., 15.16 , 24.76 , 31.94 ],
       [15.51 ,  0.   , 17.55 , ...,  1.86 , 10.65 , 16.77 ],
       [11.67 , 18.11 ,  0.   , ..., 18.01 , 23.91 , 31.09 ],
       ...,
       [15.121,  2.167, 17.156, ...,  0.   , 15.432, 18.173],
       [26.424, 10.423, 24.087, ..., 11.239,  0.   ,  8.665],
       [32.06 , 11.135, 26.674, ..., 12.298,  5.247,  0.   ]])

In [14]:
dm = pd.read_csv('lat_lon.csv')
dm.to_numpy

<bound method DataFrame.to_numpy of      Latitude (y)  Longitude (x)
0       25.686514    -100.273998
1       25.743325    -100.354555
2       25.625977    -100.304001
3       25.763782    -100.408236
4       25.636985    -100.287403
..            ...            ...
101     25.644937    -100.278932
102     25.737479    -100.408655
103     25.745256    -100.343669
104     25.762550    -100.425484
105     25.799771    -100.412473

[106 rows x 2 columns]>

In [12]:
[tuple(array) for array in dm.to_numpy()]

[(25.6865137, -100.2739976),
 (25.7433246, -100.3545548),
 (25.6259766, -100.304001),
 (25.7637822, -100.4082355),
 (25.6369853, -100.2874034),
 (25.6649542, -100.2953957),
 (25.7465622, -100.3473322),
 (25.7717833, -100.4039948),
 (25.8002997, -100.4110857),
 (25.7425771, -100.4049836),
 (25.6492493, -100.3028621),
 (25.6780351, -100.2992577),
 (25.754633, -100.382495),
 (25.6297501, -100.3375475),
 (25.2127681, -99.83258),
 (25.7699915, -100.3986161),
 (25.647045, -100.2856077),
 (25.73872, -100.3333461),
 (25.701343, -100.2986862),
 (25.7253013, -100.3591209),
 (25.7325628, -100.3830169),
 (25.8178916, -100.5373418),
 (25.7427168, -100.3797585),
 (25.4300108, -100.1508695),
 (25.7825339, -100.3933068),
 (25.6914273, -100.2928825),
 (25.7396138, -100.3392873),
 (25.694308, -100.3042185),
 (25.6966125, -100.2902852),
 (25.6385131, -100.2856473),
 (25.6719931, -100.366999),
 (25.6559027, -100.302269),
 (25.756333, -100.3621005),
 (25.7599235, -100.3872246),
 (25.7336326, -100.3207445),